services:
    keycloak:
        image: quay.io/keycloak/keycloak:26.0.0
        environment:
            - KC_HOSTNAME=8082-${HOSTNAME}-${GITPOD_WORKSPACE_CLUSTER_HOST}
            - KC_HOSTNAME_PORT=8082
            - KC_BOOTSTRAP_ADMIN_USERNAME=admin
            - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
            - KEYCLOAK_STATISTICS=all
            - KC_HEALTH_ENABLED=true
            - KEYCLOAK_LOGLEVEL=INFO
            - JAVA_OPTS_APPEND="-Dkeycloak.profile.feature.upload_script=enabled -Dkeycloak.profile.feature.scripts=enabled -Dkeycloak.profile.feature.account2=enabled -Dkeycloak.profile.feature.account_api=enabled"
        command: start-dev --http-port 8082
        ports:
            - "8082:8082"
